services:
  ros2:
    build:
      context: .
    image: ros2-humble-dev:latest
    container_name: ros2-workspace
    pull_policy: never
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /root/Drone
    #devices:
      ## Flight Controller
      #- /dev/ttyAMA0:/dev/ttyAMA0
      ## H.264 decoder
      #- /dev/video10:/dev/video10
      ## H.264 encoder
      #- /dev/video11:/dev/video11
    device_cgroup_rules:
      - 'c 189:* rmw'
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - workspace:/root/Drone
      - ./config/mavlink-router/main.conf:/root/Drone/config/mavlink-router/main.conf 
      - ./ros2_ws/src:/root/Drone/ros2_ws/src
      - ./run.sh:/root/Drone/run.sh
      - ./run_mavrouter.sh:/root/Drone/run_mavrouter.sh
      - ./data:/root/Drone/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Oak D, gets new device num each time its plugged in
      - /dev/bus/usb:/dev/bus/usb
    command: /bin/bash 
volumes:
  workspace:
