services:
  ros2:
    build:
      context: .
    image: ros2-humble-dev:latest
    container_name: ros2-workspace
    pull_policy: never
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /home/Drone
    devices:
      - /dev/dri:/dev/dri
      ## H.264 decoder
      #- /dev/video10:/dev/video10
      ## H.264 encoder
      #- /dev/video11:/dev/video11
    device_cgroup_rules:
      - 'c 189:* rmw'
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - workspace:/home/Drone
      - ./config/mavlink-router/main.conf:/home/Drone/config/mavlink-router/main.conf 
      - ./ros2_ws/src/controls_py:/home/Drone/ros2_ws/src/controls_py
      - ./ros2_ws/src/drone_launch:/home/Drone/ros2_ws/src/drone_launch
      - ./ros2_ws/src/perception_py:/home/Drone/ros2_ws/src/perception_py
      - ./run.sh:/home/Drone/run.sh
      - ./run_mavrouter.sh:/home/Drone/run_mavrouter.sh
      - ./data:/home/Drone/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Oak D, gets new device num each time its plugged in
      - /dev/bus/usb:/dev/bus/usb
    # entrypoint: ["/bin/bash", "/entrypoint.sh"]
    command: /bin/bash
volumes:
  workspace:
