#Anything recieved on one endpoint gets forwarded to other endpoints, this is how pixhawk info gets displayed in QGC
[General]
TcpServerPort=5760
ReportStats=false

[UartEndpoint flight_controller]
Device=/dev/ttyAMA0
Baud=57600

[UdpEndpoint qgc]
Mode=normal
Address=
Port=14550

#used so mavros can recieve mavlink fro mavlink-routerd
[UdpEndpoint mavros]
Mode=Normal
Address=127.0.0.1
Port=14550
