#Anything recieved on one endpoint gets forwarded to other endpoints, this is how pixhawk info gets displayed in QGC
[General]
TcpServerPort=5760
ReportStats=false

[UartEndpoint pixhawk]
Device=/dev/ttyAMA0
Baud=921600

[UdpEndpoint aidan_mac]
Mode=normal
Address= 137.146.134.34
Port=14550

[UdpEndpoint mavros]
Mode=Normal
Address=127.0.0.1
Port=14550
#need to run mavlink-routerd -c ~/drone/config/mavlink-router/main.conf
#Also need ros2 run mavros mavros_node --ros-args -p fcu_url:=udp://127.0.0.1:14550@
#Can always compile mavlink-routerd and run it from bash script 